apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: flask-fleet
  namespace: fleet
spec:
  repo: "https://github.com/YOUR_GITHUB_USER/flask.git"
  branch: "main"
  paths:
    - "k8s/"
